language: node_js
node_js:
- '0.10'
- '0.12'
addons:
  sauce_connect: true
env:
  global:
  - USE_SAUCELABS=true
  - secure: Ocah5Ak+Cwss7exkH8KgEE89B+xej61Wwslwz365fjrsxFMSUaWF3f2LIe+E8aVpl2xfnZLKMiCVuVoc26pZXF/rJFrQlWv+Ri4hM9i6yHo8E8EskVLiUIXY4Ezni8xo4t8FYWmp0Gn4/EsQCHhIoJkF5L+e3zKI9SrFeFH7vN0=
  - secure: PFui5ypMXarNsj+yC7wHQg4pje2YjfGwVyW/E2fv2MX4oSmPWWLm3ekZPP4gEqSJc8HNtMuByRVi9nOAGHemibboOhorGqe1bK1OKEc8xAeCAZpqbipJzxVn4bESNx6tiNR859VVB3EiaTLtDe1SnyZcjR9OR3A7fTHtZAQ9rgE=
